"""Add SystemMetadata table

Revision ID: 9258f11ac071
Revises: d66b6dd14976
Create Date: 2026-03-03 15:53:00.932558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9258f11ac071'
down_revision: Union[str, Sequence[str], None] = 'd66b6dd14976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'system_metadata' not in tables:
        op.create_table('system_metadata',
            sa.Column('key', sa.Text(), nullable=False),
            sa.Column('value', sa.Text(), nullable=True),
            sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
            sa.PrimaryKeyConstraint('key')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_metadata')
    # ### end Alembic commands ###
