"""Add C2CItem status fields

Revision ID: d66b6dd14976
Revises: 0001_baseline_schema
Create Date: 2026-03-03 14:56:41.393591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66b6dd14976'
down_revision: Union[str, Sequence[str], None] = '0001_baseline_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c2c_items', sa.Column('publish_status', sa.Integer(), nullable=True))
    op.add_column('c2c_items', sa.Column('sale_status', sa.Integer(), nullable=True))
    op.add_column('c2c_items', sa.Column('drop_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c2c_items', 'drop_reason')
    op.drop_column('c2c_items', 'sale_status')
    op.drop_column('c2c_items', 'publish_status')
    # ### end Alembic commands ###
