"""Add created_at to C2CItem

Revision ID: f94b7650f2af
Revises: 9258f11ac071
Create Date: 2026-03-03 16:08:54.434283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94b7650f2af'
down_revision: Union[str, Sequence[str], None] = '9258f11ac071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c["name"] for c in inspector.get_columns("c2c_items")]
    
    if "created_at" not in columns:
        # D1 does not allow non-constant defaults in ALTER TABLE ADD COLUMN,
        # so we add as plain nullable TEXT and backfill immediately.
        op.add_column('c2c_items', sa.Column('created_at', sa.Text(), nullable=True))
        op.execute("UPDATE c2c_items SET created_at = updated_at WHERE created_at IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c2c_items', 'created_at')
    # ### end Alembic commands ###
